// Builds the glass layer from the @vire/vireglass core into a self-contained ES
// module, src/glass/vireglass.bundle.js, which is committed to the repository.
//
// The package is private and ships TypeScript sources, so the path to the
// monorepo is given explicitly: VIRE_REPO, otherwise the sibling ../vire folder.
// The generated module is committed precisely so that everyone else can build
// the extension (npm run build) without having that monorepo at all.
import { build } from 'esbuild';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const VIRE = resolve(process.env.VIRE_REPO || join(ROOT, '..', 'vire'));
const PKG = join(VIRE, 'packages', 'vireglass', 'src');

if (!existsSync(PKG)) {
  console.error(
    `VireGlass core not found: ${PKG}\nPoint at the monorepo: VIRE_REPO=<path> npm run build:glass`,
  );
  process.exit(1);
}

await build({
  entryPoints: [join(ROOT, 'src', 'glass', 'entry.ts')],
  outfile: join(ROOT, 'src', 'glass', 'vireglass.bundle.js'),
  bundle: true,
  format: 'esm',
  target: 'chrome111',
  legalComments: 'none',
  alias: {
    '@vire/vireglass': join(PKG, 'index.ts'),
    '@vire/vireglass/web': join(PKG, 'web', 'index.ts'),
  },
  banner: {
    js: '// Generated by: npm run build:glass. Source — src/glass/entry.ts + @vire/vireglass.\n// Do not edit by hand. Types live in vireglass.bundle.d.ts next to this file.',
  },
});

console.log('src/glass/vireglass.bundle.js built from', PKG);
